version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MinhaSenhaSuperForte123
    ports:
      - "1433:1433"
    volumes:
    - sql_data:/var/opt/mssql
volumes:
   sql_data:
  