// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using measurement_generator.Repository;

#nullable disable

namespace measurement_generator.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("measurement_generator.Models.Erp.Erp", b =>
                {
                    b.Property<int>("CodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("AssociatedGroups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Authenticated")
                        .HasColumnType("bit");

                    b.Property<string>("DnsIot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IndexH")
                        .HasColumnType("float");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ScopeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("haveFile")
                        .HasColumnType("bit");

                    b.HasKey("CodId");

                    b.ToTable("Erps");
                });
#pragma warning restore 612, 618
        }
    }
}
